const data = {
	products: [
		{
			id: "1",
			name: "Inglot All covered under eye concealer",
			category: "Face",
			image: "/images/p-1.jpg",
			price: 22,
			countInStock: 10,
			brand: "Inglot",
			rating: 5,
			numReviews: 10,
			dedcription:
				"Was developed especially for the delicate under eye skin. Waterproof and silky formula perfectly covers imperfections and shades under eyes. It provides very natural and long-lasting effect.",
		},
		{
			id: "2",
			name: "Inglot Sparkler face eyes body highlighter",
			category: "Face",
			image: "/images/p-2.jpg",
			price: 25,
			countInStock: 20,
			brand: "Inglot",
			rating: 5,
			numReviews: 11,
			dedcription:
				"A delicate, baked Soft Sparkler for face, eyes and body adds a sophisticated finish to your makeup. A subtle combination of colors with the diversity of shimmering particles brings out the inner glow of your skin.",
		},
		{
			id: "3",
			name: "Inglot Mattifying loose powder",
			category: "Face",
			image: "/images/p-3.jpg",
			price: 17,
			countInStock: 30,
			brand: "Inglot",
			rating: 5,
			numReviews: 6,
			dedcription:
				"Loose powder ideal to combat shiny skin. Unique spherical polymers and hybrid silicone powder provide the soft focus effect and make this the ultimate mattifier. Perfect for setting foundation without buildup, and mattifying any surface.Perfect for Sport, on Stage, and in the Studio.",
		},
		{
			id: "4",
			name: "Inglot Mattifying under makeup",
			category: "Face",
			image: "/images/p-4.jpg",
			price: 26,
			countInStock: 2,
			brand: "Inglot",
			rating: 5,
			numReviews: 20,
			dedcription:
				"Hypoallergenic Mattifying Under Makeup Base with its smooth, gel consistency softens and thoroughly mattifies the skin preparing it for long-lasting, flawless makeup. Moreover, the product’s special formula gives the effect of evening out minor wrinkles, giving the soft and velvety feel to your skin. It absorbs the excess of sebum without drying out the skin.",
		},
		{
			id: "5",
			name: "Inglot Cream foundation",
			category: "Face",
			image: "/images/p-5.jpg",
			price: 23,
			countInStock: 0,
			brand: "Inglot",
			rating: 2.5,
			numReviews: 10,
			dedcription:
				"Long lasting and transfer resistant foundation that blends perfectly without clogging pores. Protects the skin and smoothes textural difference. Provides fairly strong coverage.",
		},
		{
			id: "6",
			name: "Inglot Starlight stick highlighter",
			category: "Face",
			image: "/images/p-6.jpg",
			price: 28,
			countInStock: 7,
			brand: "Inglot",
			rating: 5,
			numReviews: 16,
			dedcription:
				"Add more glow and radiance to your skin with Starlight Stick Highlighter and enjoy it for hours!",
		},
		{
			id: "7",
			name: "Inglot Secret volume mascara",
			category: "Face",
			image: "/images/p-7.jpg",
			price: 29,
			countInStock: 9,
			brand: "Inglot",
			rating: 5,
			numReviews: 7,
			dedcription:
				"This is the key to unleashing the secret to thicker, longer, and more defined lashes. With a densely packed silicone brush intense, yet very natural volume can be achieved. Secret Volume Mascara is suitable for most lash types and will not smudge or flake.",
		},
		{
			id: "8",
			name: "Inglot Makeup brush 15bjf",
			category: "Face",
			image: "/images/p-8.jpg",
			price: 14,
			countInStock: 11,
			brand: "Inglot",
			rating: 4,
			numReviews: 9,
			dedcription:
				"Best for: bronzing powder, blush, pressed powder, loose powder. A classic brush for blush and sculpting powder application. Synthetic version available",
		},
	],
};

export default data;
