export const USER_SIGNIN = {
	REQUEST: "USER_SIGNIN_REQUEST",
	SUCCESS: "USER_SIGNIN_SUCCESS",
	FAIL: "USER_SIGNIN_FAIL",
};

export const USER_REGISTER = {
	REQUEST: "USER_REGISTER_REQUEST",
	SUCCESS: "USER_REGISTER_SUCCESS",
	FAIL: "USER_REGISTER_FAIL",
};

export const USER_SIGNOUT = "USER_SIGNOUT";
